steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- task: DotnetGlobalToolInstaller@0
  inputs:
    name: 'cake.tool'
    versionSpec: '1.0.0'
    checkLatest: true

- task: Cake@2
  inputs:
    script: 'build.cake'
    target: 'Default'
